// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpqirqzaibxmhlbxihne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwcWlycXphaWJ4bWhsYnhpaG5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjg4MTIsImV4cCI6MjA2OTcwNDgxMn0.g_vF4Ya1ly9h_D-TaJftVnzANO4SaHy2c95YJ3vs4rY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});